version: '3'

services:
   jenkins:
     image: jenkins-docker:latest
     volumes:
       - /home/stephen/dev/my-jenkins/home:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
     restart: always
     ports:
       - "18080:8080"
     environment:
       JAVA_OPTS: -Xms512m -Xmx512m -Xmn128m
